### ISSUE TITLE
Hello Vue

### ISSUE THREAD

**Issue by FrankFang** [jirengu-inc/jrg-project-5#2]
# Vue.js 是什么

我不讲 Vue.js 是什么，我们先学再悟。

# 安装

去官网找 installation 关键字，你会看到这个页面（注意看网址）：
英文：https://vuejs.org/v2/guide/installation.html#NPM
中文：https://cn.vuejs.org/v2/guide/installation.html#NPM

copy 它给的命令，在我们任务一的项目目录里运行（最好把任务一的代码复制一份，改名为任务二）：

```
npm install vue
```

如果你注意看文档里的解释（点右上角的「Translations」有中文文档），你会发现有两个构建版本（不是 Vue 1 和 Vue 2，而是 standalone 和 runtime-only ），但是两个版本效果不同。你现在只要记住我们下面使用的 Vue 是 「独立构建」（standalone build）版本就行了，另一个版本以后学。

[按照文档](https://cn.vuejs.org/v2/guide/installation.html#独立构建-vs-运行时构建)，我们需要添加 webpack 配置（下面是修改后的 webpack.config.js）：

```
module.exports = {
  entry: './app.js',
  output: {
    filename: 'bundle.js'
  },
  module: {
    loaders:[
      {
        test: /\.js[x]?$/,
        exclude: /node_modules/,
        loader: 'babel-loader?presets[]=es2015&presets[]=react'
      },
    ]
  },
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.common.js'
    }
  }
}

```

# 解决警告

安装 vue 时，你的控制台有很多警告，如下：

```
npm http request GET https://registry.npm.taobao.org/vue
npm http 200 https://registry.npm.taobao.org/vue
/Users/frank/jrg/jrg-project-5/step-2
├── vue@2.1.8
└── UNMET PEER DEPENDENCY webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc

npm WARN enoent ENOENT: no such file or directory, open '/Users/frank/jrg/jrg-project-5/step-2/package.json'
npm WARN babel-loader@6.2.10 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm WARN step-2 No description
npm WARN step-2 No repository field.
npm WARN step-2 No README data
npm WARN step-2 No license field.
```

## npm WARN step-2 No xxx

最后四行警告说我们没有 description、repository field、README data 和 license field。
要解决这个问题，我们必须要有如下几个文件：

* package.json
* README.md 

1. package.json

    使用 `npm init` 可以创建一个初始的 package.json，你敲完这个命令之后，npm 会问你很多问题，方便起见，我们先不回答，一路回车就行（你看得懂也可以回答一下）。

    ```
    This utility will walk you through creating a package.json file.
    It only covers the most common items, and tries to guess sensible defaults.

    See `npm help json` for definitive documentation on these fields
    and exactly what they do.

    Use `npm install <pkg> --save` afterwards to install a package and
    save it as a dependency in the package.json file.

    Press ^C at any time to quit.
    name: (step-2)
    version: (1.0.0)
    description:
    entry point: (app.js)
    test command:
    git repository:
    keywords:
    author:
    license: (ISC)
    About to write to /Users/frank/jrg/jrg-project-5/step-2/package.json:

    {
      "name": "step-2",
      "version": "1.0.0",
      "description": "",
      "main": "app.js",
      "dependencies": {
      },
      "devDependencies": {},
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC"
    }


    Is this ok? (yes)
    ```
    这时 package.json 就创建好了，你需要
    1. 把里面的 description 改一下
    2. 如果你这个目录有对应的 git 远程仓库的话，你也可以加上 repository 字段，只需要把 FrankFang/xxx 改成你的仓库名就行了。

    文件结果如下：

    ```
    {
      "name": "step-2",
      "version": "1.0.0",
      "description": "A vue.js demo",
      "main": "app.js",
      "dependencies": {
      },
      "repository": {
        "type": "git",
        "url": "git+https://github.com/FrankFang/xxx.git"
      },
      "devDependencies": {},
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC"
    }

    ```

2. README.md

    这个文件对于开源项目来说非常重要，只是你现在还不知道怎么写而已。那么我们就创建一个空文件来掩盖这个警告吧：

    ```
    touch README.md
    ```

    重新运行 `npm i vue` 是不是警告变少了：

    ```
    # npm i vue
    npm http request GET https://registry.npm.taobao.org/vue
    npm http 304 https://registry.npm.taobao.org/vue
    step-2@1.0.0 /Users/frank/jrg/jrg-project-5/step-2
    ├── vue@2.1.8
    └── UNMET PEER DEPENDENCY webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc

    npm WARN babel-loader@6.2.10 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
    npm WARN step-2@1.0.0 No repository field.
    ```

## 警告 babel-loader@6.2.10 requires a peer of webpack

记不记得上一篇教程我要你全局安装 webpack 命令：

`npm i -g webpack`

同样，任何想要启动你的项目的人，都必须全局安装 webpack。如果他忘了安装，那么这个项目根本就无法运行。这就很麻烦了。你需要在 README.md 里警告其他人一定要安装 webpack 才行。

npm 想了另一个办法来解决这个麻烦，把你依赖的命令都声明在 package.json 里：

`npm i -S webpack vue babel-loader babel-core babel-preset-es2015 babel-preset-react`

运行之后，我们依赖的所有包（任务一需要的包我也写在上面了），都会被安装，同时 package.json 的 dependencies 字段，会记录这些包的名字和版本，就像这样：

```
// 这是 package.json 文件的内容
{
  省略...
  "main": "app.js",
  "dependencies": {
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "vue": "^2.1.8",
    "webpack": "^1.14.0"
  },
  省略...
}

```

好处：

1. 别人 git clone 你的项目之后，只需要运行 `npm i` 就可以安装你指定的包
2. 不需要全局安装 webpack 了，转而使用 `./node_modules/.bin/webpack` 这个文件作为 webpack 命令（原来命令就是文件啊？你才知道）

我们来试一下：

```
# ./node_modules/.bin/webpack
Hash: 61a3dfaceb637bce005a
Version: webpack 1.14.0
Time: 627ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.83 kB       0  [emitted]  main
    + 2 hidden modules
```

然后你就可以把全局安装的 webpack 卸载掉了。（不过没必要卸载）

至此就没有警告了。其实程序员从来都不在乎警告的 😄 

# copy-run-modify Vue

1. Copy

    先抄 [https://cn.vuejs.org/v2/guide/#起步](https://cn.vuejs.org/v2/guide/#起步)。
    先不要管你抄的东西是什么意思。

    ```
    改写 page.html
    <html>
      <head>
      </head>
      <body>
        <div id="app">
          {{ message }}
        </div>

        <script src="bundle.js"></script>
      </body>
    </html>

    ```

    ```
    改写 app.js 
    import bar from './bar';

    var app = new Vue({
      el: '#app',
      data: {
        message: 'Hello Vue!'
      }
    })                                                               
    ```

2. Run

    然后运行 `webpack`，打开 page.html

    看到浏览器控制台报错：

    ```
    Uncaught ReferenceError: Vue is not defined
    ```

    app.js 里的 Vue 确实不知道是从哪来的，仿照 `import bar from './bar'`，我们在 app.js 里加一句 `import Vue from 'vue'`，结果如下：

    ```
    import bar from './bar'
    import Vue from 'vue'

    var app = new Vue({
      el: '#app',
      data: {
        message: 'Hello Vue!'
      }
    })                                                               

    ```

    然后运行 `webpack`，刷新 page.html。

    没有报错，页面看起来是这样：

    ![](https://ww4.sinaimg.cn/large/652c38b1gw1fbmmkv3us7j20ww0kw78b.jpg)

## Modify

现在我们来看看我们 copy 了些什么玩意。

```
<div id="app">
  {{ message }}
</div>
```

```
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
```

1. div 里的 {{message}} 怎么变成了 Hello Vue!

    看起来 `Hello Vue!` 和 message 有某种对应关系，那么我们把 Hello Vue! 改成 Hello Frank! 试试。

    改完之后保存，运行 `webpack`，刷新 page.html，页面变成了：

    ![](https://ww1.sinaimg.cn/large/652c38b1gw1fbmmpyc9qaj20ro05aq3q.jpg)

    看来我们的猜测是对的，data 的 message 与页面中的 {{message}} 存在绑定关系。

    接下来我们可以继续「猜测」，然后通过 modify 来验证。

2. `div id="app"` 与 `el: '#app'`

    我们猜测 `div id="app"` 与 `el: '#app'` 有对应关系，那么我们试着把 div 的 id=app 改成 id=xxx。

    改 HTML 是不需要运行 `webpack` 的，然后我们直接刷新 page.html 试试：

    ![](https://ww4.sinaimg.cn/large/652c38b1gw1fbmmugfgqxj210k0l8dkj.jpg)

    果然报错，找不到 #app，说明我们的猜测正确。

你还可以继续猜，然后 modify，比如改 data、改 el 等。

每次改完 JS 你都要运行 webpack 重新打包。

至此，Vue 的 Hello World 我们就做出来了。

# 致饥人谷学员

你需要看懂本教程，并将上面的操作全部实现，最终做出一个 Vue 的 Hello World。

不要把 node_modules、.DS_Store、.idea 提交上来！

任务截止时间，本周六 21:00。

有没有发现今天的教程比上次长很多，以后会越来越长的。

**Comment by joyce-song** [comment]
[Vue-test](https://github.com/joyce-song/vue-test) SJ

**Comment by FrankFang** [comment]
所有代码在这里：https://github.com/jirengu-inc/jrg-project-5/tree/master/step-2

**Comment by starlikerain** [comment]
[Link](https://github.com/starlikerain/graduation-project)

Vue我来了 正如我悄悄的走
![image](https://cloud.githubusercontent.com/assets/20137345/21837512/7b93f9a2-d807-11e6-93cc-7ac66c339545.png)

**Comment by FrankFang** [comment]
@starlikerain  你的 README 怎么还是 npm i xxxxxx

**Comment by 0xjeso** [comment]
[Vue-test](https://github.com/joyce-song/vue-test) SJ

**Comment by TerenYeung** [comment]
yjl v-o-r for task-02 [link](https://github.com/TerenYeung/mywork/tree/master/vue-online-resume/task-02)

**Comment by nineSean** [comment]
[Vue.js-demo](https://github.com/nineSean/tool-for-online-resume/tree/master/step-2) LX

**Comment by lzm320856** [comment]
[vue](https://github.com/lzm320856/vue-text) LZM

**Comment by chaocool** [comment]
[vue-test](https://github.com/chaocool/webpack-demo/tree/master/%E4%BB%BB%E5%8A%A12-vue) **CJC**

**Comment by whiteblank** [comment]
[vue-demo](https://github.com/jirengu-inc/jrg-renwu8/tree/master/homework/%E9%A1%BE%E5%98%89%E8%AF%9A/webpack/vue)GJC

**Comment by WangXiaoyugg** [comment]
[vue-demo](https://github.com/WangXiaoyugg/helllo-vue) WXY

**Comment by LYangTou** [comment]
[hello vue](https://github.com/Hungereeeeee/vue/tree/master/task02)

**Comment by wlf1112** [comment]
[vue-demo](https://github.com/wlf1112/webpack-demo/tree/master/task2) WLF

**Comment by zhangjiuyi** [comment]
[vue-demo](https://github.com/zhangjiuyi/Project5/tree/master/vue-task2)  ZJY

**Comment by Rice-F** [comment]
[Vue.js-demo](https://github.com/Rice-F/Online-resume/tree/master/demo2-Vue.js)SJ

**Comment by LisaLi85** [comment]
[Vue-demo LLL](https://github.com/LisaLi85/graduation-project/tree/master/task2)

**Comment by Panda-HJN** [comment]
[vue-demo](https://github.com/Panda-HJN/my-vue-project/tree/master/task2-my-first-vue)
HJN

**Comment by xiaokunxu** [comment]
[Vue.js-demo](https://github.com/xiaokunxu/webpack-demo/tree/master/step-2)  xxk

**Comment by wuhanjun** [comment]
[Hello-Vue](https://github.com/WuHanJun/Online-Resume-Editor/tree/master/Hello-Vue)  WHJ

**Comment by Zegendary** [comment]
[vue-demo](https://github.com/Zegendary/jrg-pro/tree/master/vue-step1) zxw

**Comment by ReedSun** [comment]
[vue demo](https://github.com/ReedSun/Ferris-wheel/tree/master/demo2l)  SHZ

**Comment by JayChenFE** [comment]
[task2](https://github.com/JayChenFE/graduate_project/tree/master/task2)
任务3陈捷

**Comment by JaeJiang** [comment]
# [✌️step-2  Josh/姜杭轩](https://github.com/JaeJiang/graduation-project/tree/master/step-2)

**Comment by mimi3824ku** [comment]
[task2](https://github.com/mimi3824ku/resume) LWE

**Comment by Hsyneve** [comment]
[难道我又是最后一个。。。不开心 hsy](https://github.com/Hsyneve/webpackuse/tree/master/task2)

**Comment by have-not-BUG** [comment]
[任务二](https://github.com/have-not-BUG/onlineResume/tree/master/vue) LC

**Comment by muxi7** [comment]
[任务二](https://github.com/muxi7/online-Resumer-item/tree/master/task-2) ZW

**Comment by GuoQichen** [comment]
[vue2-demo](https://github.com/GuoQichen/vue2-demo) GQC

**Comment by myql** [comment]
[task2](https://github.com/myql/task2) WQ

**Comment by cxxgo** [comment]
[task2-vue](https://github.com/candy252324/vue)CJH

**Comment by yukui630** [comment]
[task2vue](https://github.com/yukui630/webpack/tree/master/task2-vue.demo)

**Comment by sen-lin** [comment]
[二啊啊啊啊](https://github.com/sen-lin/webpack/tree/master/step-2)

**Comment by lightbuild** [comment]
[vue-test](https://github.com/lightbuild/vue-onlineResume/tree/master/step02-vue) 任务6-任磊。最后挤一挤~~

**Comment by baixiaoji** [comment]
[vue-demo](https://github.com/baixiaoji/tool-for-online-resume/tree/master/step-2) ZLJ

**Comment by ab690257072** [comment]
[step-2](https://github.com/ab690257072/graduation-project/tree/master/step-2) 任务6班-赵力群

**Comment by batman-1** [comment]
[vue-demo](https://github.com/batman-1/online-resume/tree/master/Hello%20Vue)

**Comment by code-zhangrui** [comment]
[demo-2](https://github.com/code-zhangrui/vue-demos/tree/master/demo-2)  任务10班 张睿

**Comment by FrankFang** [comment]
@code-zhangrui   README.md 呢

**Comment by code-zhangrui** [comment]
已补充！

2017-02-07 19:16 GMT+08:00 Frank Fang <notifications@github.com>:

**Comment by sfyr111** [comment]
[Hello Vue](https://github.com/sfyr111/Vue-task/tree/task2)

**Comment by JeromeYangtao** [comment]
[hello-Vue](https://github.com/JeromeYangtao/hello-Vue)直播11班杨涛

**Comment by superDCF** [comment]
[hello vue](https://github.com/dingchaofa/webpack/tree/master/task2) 直播11班 丁超发

**Comment by MasterGaoJin** [comment]
[task-2](https://github.com/MasterGaoJin/design/tree/master/task2) LK

**Comment by n313893254** [comment]
[hello vue](https://github.com/n313893254/demo/tree/master/vue-demo) 弄庆洋

**Comment by success-cg** [comment]
[陈功 task-2](https://github.com/18810666595/vue-resume/tree/master/task-2)

**Comment by boloog** [comment]
[vue-demo](https://github.com/boloog/vue-demo) boloog

**Comment by kumabearplus** [comment]
[vue-demo](https://github.com/kumabearplus/webpack/tree/master/demo2) 熊凡

**Comment by Honohonoho** [comment]
[hello Vue.js](https://github.com/Honohonoho/Vue.js-demo)  李祺

**Comment by komolei** [comment]
[second](https://github.com/komolei/vue/tree/master/second )空末

**Comment by swhzzz** [comment]
[first vue](https://github.com/swhzzz/myVue/tree/master/step2)沈文豪

**Comment by selectyang** [comment]
<a href="https://github.com/selectyang/Sample/tree/master/webpack_sample/step_2">webpack_setp_2</a> 杨家文

**Comment by 0xJett** [comment]
[vuejs-step2](https://github.com/SpontaLeo/Online-resume/tree/master/try-vuejs )

**Comment by jamesXiao-coder** [comment]
[dmo2](https://github.com/xiaohongjian1989/webpack-demo2)

**Comment by zhaipanyu** [comment]
[step2](https://github.com/zhaipanyu/vue-test/tree/master/step2)

**Comment by robbchan** [comment]
[step2](https://github.com/kmac007/vue-learn/tree/master/vue-start) 任务班-陈登科

**Comment by zhaipanyu** [comment]
为什么抄送给我??

**Comment by wpsumsun** [comment]
[Hello Vue](https://github.com/wpsumsun/webpack-vue) 王朽木

**Comment by imgwho** [comment]
[vuejs](https://github.com/imgwho/jirengu/tree/master/vue2-vuejs) 1705郭文华

**Comment by anotherLee** [comment]
[hello vue](https://github.com/liyue2/online-resumer/commit/064baf644a1936c1d745cd236b197476eae8151c)

**Comment by forsuccess** [comment]
[预览](https://forsuccess.github.io/webpack-vue/page.html)

**Comment by forsuccess** [comment]
[预览]https://forsuccess.github.io/webpack-vue/step2/page.html

**Comment by forsuccess** [comment]
[预览](https://forsuccess.github.io/webpack-vue/step2/page.html)

**Comment by Xiny-Huang** [comment]
![image](https://user-images.githubusercontent.com/26321899/28558718-b605d97a-7145-11e7-82a6-160f7a5f2fc0.png)
https://github.com/HuangHongRui/Vue_ToDo

**Comment by fangyc1993** [comment]
[Vue-demo](https://github.com/fangyc1993/Vue-demo)

**Comment by huoguozhang** [comment]
[vue-2](https://github.com/huoguozhang/vue-study-log/tree/master/demo)好像把任务1覆盖了。。

**Comment by andreaxiang** [comment]
[hello vue](https://andreaxiang.github.io/hello-vue/page.html)

**Comment by zhuyutrisla** [comment]
[step-2](https://github.com/zhuyutrisla/webpack-demo/tree/master/step-2)

**Comment by chenshangshuo** [comment]
[hello vue](https://github.com/chenshangshuo/vue-test)

**Comment by clementlxd** [comment]
代码 https://github.com/clementlxd/vueTask1

预览 https://clementlxd.github.io/vueTask1/page.html

**Comment by Zainking** [comment]
https://github.com/Zainking/resumer/tree/practice/task2

**Comment by xzmly** [comment]
https://github.com/xzmly/webpack

你好方方，再见方方

**Comment by Alfred-ZF** [comment]
https://github.com/Zhangfan4132/vue-test-02 1704张帆

**Comment by ZhouChilly** [comment]
https://github.com/ZhouChilly/project/tree/master/VueResume/Task2

**Comment by tang-yue** [comment]
[Hello](https://github.com/tang-yue/webpack-demo)

**Comment by blackhu0804** [comment]
https://github.com/hu970804/vue-resume

**Comment by nciilin** [comment]
代码： https://github.com/nciilin/vue/tree/master/task2
预览： http://bloglive.top/vue/task2/page.html

**Comment by wobenng** [comment]
任务15董杭彬
code: https://github.com/wobenng/webpack-demo
demo: https://wobenng.github.io/webpack-demo/page.html

**Comment by melongain** [comment]
任务15：王峻名
我也要学Vue啊啊啊啊啊[code](https://github.com/WjmNightingale/vue-resume)

**Comment by upupdayday** [comment]
[源码](https://github.com/upupdayday/Vue/tree/master/Vue_resume/hello_vue)
[预览](https://upupdayday.github.io/Vue/Vue_resume/hello_vue/page.html)
任务班-孙翰卿
